#!/bin/bash
# Concatenate the PaleTools prod blob + loader, then embed as a base64 C header.
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
PROD="$DIR/../www/js/paletools-mobile.prod.js"
LOADER="$DIR/inject-loader.js"
OUT_JS="$DIR/inject.js"
OUT_H="$DIR/injectjs.h"

if [ ! -f "$PROD" ]; then
    echo "error: $PROD not found" >&2
    exit 1
fi

cat "$PROD" "$LOADER" > "$OUT_JS"

{
    echo "// AUTO-GENERATED by build-inject.sh — do not edit."
    echo "static const char *kPaleToolsJSBase64 ="
    # base64, wrapped, each line a separate adjacent C string literal
    base64 < "$OUT_JS" | fold -w 120 | sed 's/^/    "/; s/$/"/'
    echo "    ;"
} > "$OUT_H"

echo "generated $OUT_H ($(wc -c < "$OUT_H") bytes)"
