#!/bin/bash
# Decode the PaleTools blob, wrap it in a load-waiter, gzip it, and embed the
# compressed bytes as a C array. Everything this script writes goes into
# generated/ — it is machine output, never hand-edited, and gitignored.
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"
PROD="paletools-mobile.prod.js"
GEN="generated"
OUT_JS="$GEN/inject.js"
OUT_GZ="$GEN/pt_payload.gz"
OUT_H="$GEN/injectjs.h"

if [ ! -f "$PROD" ]; then
    echo "error: $PROD not found" >&2
    exit 1
fi

mkdir -p "$GEN"

# Decode prod.js -> raw self-executing bundle, then wrap so it runs after the
# app's SPA has booted (the bundle is an IIFE; we just delay it to load).
node -e '
const fs = require("fs");
const src = fs.readFileSync(process.argv[1], "utf8");
const m = src.match(/=\s*"([^"]*)";?\s*$/s);
if (!m) { console.error("could not find paletools blob"); process.exit(1); }
const bundle = decodeURIComponent(m[1]);
const wrapped =
  "/*__PALETOOLS_INJECTED__*/\n(function(){function boot(){\n" + bundle +
  "\n}\nif(document.readyState===\x27complete\x27)setTimeout(boot,0);" +
  "else addEventListener(\x27load\x27,function(){setTimeout(boot,0)});})();\n";
fs.writeFileSync(process.argv[2], wrapped);
' "$PROD" "$OUT_JS"

gzip -9 -n -c "$OUT_JS" > "$OUT_GZ"

# Header carries a banner so it is never mistaken for authored source.
# Run xxd from inside $GEN so the C symbol is plain `pt_payload_gz`, not
# `generated_pt_payload_gz` (xxd derives the name from the path it's given).
{
    echo "/* GENERATED by build-inject.sh — DO NOT EDIT. Source: $PROD */"
    ( cd "$GEN" && xxd -i "pt_payload.gz" )
} > "$OUT_H"

echo "raw js : $(wc -c < "$OUT_JS") bytes"
echo "gzipped: $(wc -c < "$OUT_GZ") bytes  -> embedded in $OUT_H"
